springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: br.com.coffeeandit.api
spring:
  redis:
    port: 6379
    host: localhost
    timeout: 5000

limites:
  url: http://localhost:8081